version: '3'
services:
  php:
    image: php:7.4-apache
    networks:
      - app
    ports:
      - "8081:80"
    volumes:
      - ./code.php:/var/www/html/index.php
networks:
  app:
    ipam:
      driver: default
